/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkoutLogRouteRouteImport } from './routes/WorkoutLogRoute'
import { Route as OneRepMaxRouteRouteImport } from './routes/OneRepMaxRoute'
import { Route as IndexRouteImport } from './routes/index'

const WorkoutLogRouteRoute = WorkoutLogRouteRouteImport.update({
  id: '/WorkoutLogRoute',
  path: '/WorkoutLogRoute',
  getParentRoute: () => rootRouteImport,
} as any)
const OneRepMaxRouteRoute = OneRepMaxRouteRouteImport.update({
  id: '/OneRepMaxRoute',
  path: '/OneRepMaxRoute',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/OneRepMaxRoute': typeof OneRepMaxRouteRoute
  '/WorkoutLogRoute': typeof WorkoutLogRouteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/OneRepMaxRoute': typeof OneRepMaxRouteRoute
  '/WorkoutLogRoute': typeof WorkoutLogRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/OneRepMaxRoute': typeof OneRepMaxRouteRoute
  '/WorkoutLogRoute': typeof WorkoutLogRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/OneRepMaxRoute' | '/WorkoutLogRoute'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/OneRepMaxRoute' | '/WorkoutLogRoute'
  id: '__root__' | '/' | '/OneRepMaxRoute' | '/WorkoutLogRoute'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OneRepMaxRouteRoute: typeof OneRepMaxRouteRoute
  WorkoutLogRouteRoute: typeof WorkoutLogRouteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/WorkoutLogRoute': {
      id: '/WorkoutLogRoute'
      path: '/WorkoutLogRoute'
      fullPath: '/WorkoutLogRoute'
      preLoaderRoute: typeof WorkoutLogRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/OneRepMaxRoute': {
      id: '/OneRepMaxRoute'
      path: '/OneRepMaxRoute'
      fullPath: '/OneRepMaxRoute'
      preLoaderRoute: typeof OneRepMaxRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OneRepMaxRouteRoute: OneRepMaxRouteRoute,
  WorkoutLogRouteRoute: WorkoutLogRouteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
